In [1]:
from sympy.solvers import solve
from sympy import Symbol, I
import numpy as np
import sympy
from sympy.physics.quantum.dagger import Dagger

### Unitary Matrix for 2 data points (4x4) 

In [2]:
r1 = Symbol('r1')
r2 = Symbol('r2')
r3 = Symbol('r3')
r4 = Symbol('r4')
r5 = Symbol('r5')
r6 = Symbol('r6')
r7 = Symbol('r7')
r8 = Symbol('r8')
r9 = Symbol('r9')
r10 = Symbol('r10')

i1 = Symbol('i1')
i2 = Symbol('i2')
i3 = Symbol('i3')
i4 = Symbol('i4')
i5 = Symbol('i5')
i6 = Symbol('i6')
i7 = Symbol('i7')
i8 = Symbol('i8')
i9 = Symbol('i9')
i10 = Symbol('i10')

c1 = r1 + I*i1
c2 = r2 + I*i2
c3 = r3 + I*i3
c4 = r4 + I*i4
c5 = r5 + I*i5
c6 = r6 + I*i6
c7 = r7 + I*i7
c8 = r8 + I*i8
c9 = r9 + I*i9
c10 = r10 + I*i10
alpha = Symbol('alpha')

In [6]:
U = sympy.Matrix([
        [0.5,           1,    0.5,      r1],
        [1,             0,     1,       r2],
        [0.5,           1,     r5,      r6],
        [r1,            r2,    r6,      r10]
])


In [7]:
U = U/alpha

In [8]:
U

Matrix([
[0.5/alpha,  1/alpha, 0.5/alpha,  r1/alpha],
[  1/alpha,        0,   1/alpha,  r2/alpha],
[0.5/alpha,  1/alpha,  r5/alpha,  r6/alpha],
[ r1/alpha, r2/alpha,  r6/alpha, r10/alpha]])

In [9]:
Dagger(U)

Matrix([
[          0.5/conjugate(alpha),             1/conjugate(alpha),           0.5/conjugate(alpha),  conjugate(r1)/conjugate(alpha)],
[            1/conjugate(alpha),                              0,             1/conjugate(alpha),  conjugate(r2)/conjugate(alpha)],
[          0.5/conjugate(alpha),             1/conjugate(alpha), conjugate(r5)/conjugate(alpha),  conjugate(r6)/conjugate(alpha)],
[conjugate(r1)/conjugate(alpha), conjugate(r2)/conjugate(alpha), conjugate(r6)/conjugate(alpha), conjugate(r10)/conjugate(alpha)]])

In [10]:
mul = Dagger(U) * U

In [11]:
ans = solve([mul[0] - 1,
             mul[1],
             mul[2],
             mul[3],
             mul[5] - 1,
             mul[6],
             mul[7],
             mul[10] -1,
             mul[11],
             mul[15] - 1], dict=True)

In [12]:
ans

[{r1: 1.13171392427787,
  alpha: 1.66756601260772,
  r2: -0.883615530875513,
  r5: -1.06155281280883,
  r6: -0.635517137473157,
  r10: 0.561552812808830}]

In [14]:
ans[0][r1]

1.13171392427787

In [16]:
i = 0

In [23]:
U_ans = sympy.Matrix([
        [0.5,           1,           0.5,          ans[i][r1]],
        [1,             0,            1,           ans[i][r2]],
        [0.5,           1,          ans[i][r5],    ans[i][r6]],
        [ans[i][r1],   ans[i][r2], ans[i][r6],     ans[i][r10]]
])
U_ans = U_ans/ans[i][alpha]

In [24]:
U_ans

Matrix([
[0.299838205036396,  0.599676410072793,  0.299838205036396,  0.678662143340345],
[0.599676410072793,                  0,  0.599676410072793, -0.529883389439993],
[0.299838205036396,  0.599676410072793, -0.636588179887875,  -0.38110463553964],
[0.678662143340345, -0.529883389439993,  -0.38110463553964,  0.336749974851478]])

In [27]:
a = np.array(U_ans).astype(np.float64)

In [28]:
a

array([[ 0.29983821,  0.59967641,  0.29983821,  0.67866214],
       [ 0.59967641,  0.        ,  0.59967641, -0.52988339],
       [ 0.29983821,  0.59967641, -0.63658818, -0.38110464],
       [ 0.67866214, -0.52988339, -0.38110464,  0.33674997]])

In [29]:
x = np.array([0.5, 0.5, 0.5, 0.5])

In [31]:
x

array([0.5, 0.5, 0.5, 0.5])

In [30]:
a * x

array([[ 0.1499191 ,  0.29983821,  0.1499191 ,  0.33933107],
       [ 0.29983821,  0.        ,  0.29983821, -0.26494169],
       [ 0.1499191 ,  0.29983821, -0.31829409, -0.19055232],
       [ 0.33933107, -0.26494169, -0.19055232,  0.16837499]])

In [25]:
Dagger(U_ans)

Matrix([
[0.299838205036396,  0.599676410072793,  0.299838205036396,  0.678662143340345],
[0.599676410072793,                  0,  0.599676410072793, -0.529883389439993],
[0.299838205036396,  0.599676410072793, -0.636588179887875,  -0.38110463553964],
[0.678662143340345, -0.529883389439993,  -0.38110463553964,  0.336749974851478]])

In [26]:
Dagger(U_ans) * U_ans

Matrix([
[                 1.0,  5.55111512312578e-17,                     0,                     0],
[5.55111512312578e-17,                   1.0,  2.77555756156289e-17, -5.55111512312578e-17],
[                   0,  2.77555756156289e-17,                   1.0, -2.77555756156289e-17],
[                   0, -5.55111512312578e-17, -2.77555756156289e-17,                   1.0]])

### Unitary Matrix for 3 data points (8x8)

In [47]:
b[9:17]

array([b_9, b_10, b_11, b_12, b_13, b_14, b_15, b_16], dtype=object)

In [57]:
U = sympy.Matrix([
        [1/3, 2/3, 2/3, 1/3, 2/3, 1/3, b[1], b[2]],
        [1/2, 2/2, 0,   1/2,  0,  1,   b[3], b[4]],
        [1/2, 0,   2/2,  1,   0,  1/2, b[5], b[6]],
        [1,   0,    0,  1/2, 2/2, 1/2, b[7], b[8]],
        b[9:17],
        b[17:25],
        b[25:33],
        b[33:41]
])
U = U/alpha

In [58]:
U

Matrix([
[0.333333333333333/alpha, 0.666666666666667/alpha, 0.666666666666667/alpha, 0.333333333333333/alpha, 0.666666666666667/alpha, 0.333333333333333/alpha,  b_1/alpha,  b_2/alpha],
[              0.5/alpha,               1.0/alpha,                       0,               0.5/alpha,                       0,                 1/alpha,  b_3/alpha,  b_4/alpha],
[              0.5/alpha,                       0,               1.0/alpha,                 1/alpha,                       0,               0.5/alpha,  b_5/alpha,  b_6/alpha],
[                1/alpha,                       0,                       0,               0.5/alpha,               1.0/alpha,               0.5/alpha,  b_7/alpha,  b_8/alpha],
[              b_9/alpha,              b_10/alpha,              b_11/alpha,              b_12/alpha,              b_13/alpha,              b_14/alpha, b_15/alpha, b_16/alpha],
[             b_17/alpha,              b_18/alpha,              b_19/alpha,              b_20/alpha,           

In [59]:
mul = Dagger(U) * U

In [60]:
mul

Matrix([
[                                                                                                                                                       b_17*conjugate(b_17)/(alpha*conjugate(alpha)) + b_25*conjugate(b_25)/(alpha*conjugate(alpha)) + b_33*conjugate(b_33)/(alpha*conjugate(alpha)) + b_9*conjugate(b_9)/(alpha*conjugate(alpha)) + 1.61111111111111/(alpha*conjugate(alpha)),                                                               b_10*conjugate(b_9)/(alpha*conjugate(alpha)) + b_18*conjugate(b_17)/(alpha*conjugate(alpha)) + b_26*conjugate(b_25)/(alpha*conjugate(alpha)) + b_34*conjugate(b_33)/(alpha*conjugate(alpha)) + 0.722222222222222/(alpha*conjugate(alpha)),                                                               b_11*conjugate(b_9)/(alpha*conjugate(alpha)) + b_19*conjugate(b_17)/(alpha*conjugate(alpha)) + b_27*conjugate(b_25)/(alpha*conjugate(alpha)) + b_35*conjugate(b_33)/(alpha*conjugate(alpha)) + 0.722222222222222/(alpha*conjugate(alpha)),             

In [61]:
I = sympy.eye(8)

In [62]:
mul - I

Matrix([
[                                                                                                                                                  -1 + b_17*conjugate(b_17)/(alpha*conjugate(alpha)) + b_25*conjugate(b_25)/(alpha*conjugate(alpha)) + b_33*conjugate(b_33)/(alpha*conjugate(alpha)) + b_9*conjugate(b_9)/(alpha*conjugate(alpha)) + 1.61111111111111/(alpha*conjugate(alpha)),                                                               b_10*conjugate(b_9)/(alpha*conjugate(alpha)) + b_18*conjugate(b_17)/(alpha*conjugate(alpha)) + b_26*conjugate(b_25)/(alpha*conjugate(alpha)) + b_34*conjugate(b_33)/(alpha*conjugate(alpha)) + 0.722222222222222/(alpha*conjugate(alpha)),                                                               b_11*conjugate(b_9)/(alpha*conjugate(alpha)) + b_19*conjugate(b_17)/(alpha*conjugate(alpha)) + b_27*conjugate(b_25)/(alpha*conjugate(alpha)) + b_35*conjugate(b_33)/(alpha*conjugate(alpha)) + 0.722222222222222/(alpha*conjugate(alpha)),             

In [ ]:
ans = solve(mul - I, dict=True)

In [ ]:
ans