### K-Means: Combinatorial Optimization Problem

In [21]:
import numpy as np

In [22]:
dataset = [(1, 2), (3, 4), (-1, -2), (-3, -4)]

In [31]:
new_dataset = []
for d in dataset:
    d = d/np.linalg.norm(d)
    new_dataset.append(d)

new_dataset
# dataset[0]/np.linalg.norm(dataset[0])

[array([0.4472136 , 0.89442719]),
 array([0.6, 0.8]),
 array([-0.4472136 , -0.89442719]),
 array([-0.6, -0.8])]

In [32]:
dataset = [(0.4472136 , 0.89442719), (0.6, 0.8), (-0.4472136 , -0.89442719), (-0.6, -0.8)]

#### Number of clusters (K) = 2

In [37]:
def dot(v1, v2):
    return v1[0]*v2[0] + v1[1]*v2[1]

def single_dataset_obj(dataset):
    obj = 0
    
    if (len(dataset)) == 0:
        return 0
    
    for v in dataset:
        obj += dot(v, v)
    
    subtract_term = 0
    for v1 in dataset:
        for v2 in dataset:
            subtract_term += dot(v1, v2)
    subtract_term = subtract_term/len(dataset)
    obj -= subtract_term
    
    return obj

# negative of obj and remove constants, 
# prob of getting the correct cluster should be highest for the cluster with min objective
def prob_clusters(dataset):
    prob = 0
    
    if (len(dataset)) == 0:
        return 0
    
#     for v in dataset:
#         obj += dot(v, v)
    
    subtract_term = 0
    for v1 in dataset:
        for v2 in dataset:
            subtract_term += dot(v1, v2)
    subtract_term = subtract_term/len(dataset)
    prob += subtract_term
    
    return prob

def objective(dataset1, dataset2):
    return single_dataset_obj(dataset1) + single_dataset_obj(dataset2)

def prob(dataset1, dataset2):
    return prob_clusters(dataset1) + prob_clusters(dataset2)

In [46]:
for i in range(8):
    dataset1 = []
    dataset2 = []
    for j in range(4):
        if i & pow(2,j):
            dataset1.append(dataset[j])
        else:
            dataset2.append(dataset[j])

    print ("Cluster division: {}".format(i))
    print ("Objective: {}".format(objective(dataset1, dataset2)))
    print ("Probability: {}".format(prob(dataset1, dataset2)))
    print ("\n")

Cluster division: 0
Objective: 4.000000004472512
Probability: 0.0


Cluster division: 1
Objective: 2.666666668157504
Probability: 1.3333333363150082


Cluster division: 2
Objective: 2.6666666711391787
Probability: 1.3333333333333333


Cluster division: 3
Objective: 0.03226017823625593
Probability: 3.967739826236256


Cluster division: 4
Objective: 2.666666668157504
Probability: 1.333333336315008


Cluster division: 5
Objective: 4.000000004472512
Probability: 0.0


Cluster division: 6
Objective: 3.967739826236256
Probability: 0.03226017823625593


Cluster division: 7
Objective: 2.6666666711391787
Probability: 1.3333333333333333




In [35]:
for d1 in dataset:
    for d2 in dataset: 
        print (dot(d1, d2))

1.000000002236256
0.9838699120000001
-1.000000002236256
-0.9838699120000001
0.9838699120000001
1.0
-0.9838699120000001
-1.0
-1.000000002236256
-0.9838699120000001
1.000000002236256
0.9838699120000001
-0.9838699120000001
-1.0
0.9838699120000001
1.0


In [36]:
dot(dataset[0], dataset[1])

0.9838699120000001

### Unitary Matrix Construction

In [148]:
a = np.array([
        [1,  0.5, 1, -0.5],
        [0.5, 0, 0,  1],
        [1,   0, 1,  0],
        [-0.5,   1, 0,  1]
             ])

In [149]:
a_t = a.T

In [150]:
a_t

array([[ 1. ,  0.5,  1. , -0.5],
       [ 0.5,  0. ,  0. ,  1. ],
       [ 1. ,  0. ,  1. ,  0. ],
       [-0.5,  1. ,  0. ,  1. ]])

In [151]:
a_i = np.linalg.inv(a)

In [152]:
a_i

array([[ 1.33333333,  1.33333333, -1.33333333, -0.66666667],
       [ 1.33333333,  0.33333333, -1.33333333,  0.33333333],
       [-1.33333333, -1.33333333,  2.33333333,  0.66666667],
       [-0.66666667,  0.33333333,  0.66666667,  0.33333333]])

In [153]:
np.allclose(a_i, a_t)

False

In [154]:
np.matmul(a, a_t)

array([[ 2.5 ,  0.  ,  2.  , -0.5 ],
       [ 0.  ,  1.25,  0.5 ,  0.75],
       [ 2.  ,  0.5 ,  2.  , -0.5 ],
       [-0.5 ,  0.75, -0.5 ,  2.25]])